stages:
  train_model:
    cmd:
    - python train_model.py
    deps:
    - train_model.py
    params:
    - n_estimators
    - model.metric_file
    - data.clean_file
    metrics:
    - metrics.json
  slices_inference:
    cmd:
    - python compute_slices.py
    deps:
    - compute_slices.py
    params:
    - data.sliced_name
    - data.clean_file
    outs:
    - slicer.csv
