stages:
  train_model:
    cmd:
    - python train_model.py
    deps:
    - train_model.py
    params:
    - n_estimators
    - model.metric_file
    - data.clean_file
    metrics:
    - data/metrics.json
    outs:
    - model/model.pkl
    - data/test.csv
  slices_inference:
    cmd:
    - python compute_slices.py
    deps:
    - compute_slices.py
    - model/model.pkl
    - data/test.csv
    params:
    - data.clean_file
    outs:
    - data/slice_output.txt
