name: ml_deploy_fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - pytest-cov
  - requests
  - fastapi #==0.63.0
  - uvicorn
  - gunicorn
  - joblib
  - libsqlite==3.48.0
  - pylint
  - pip=23.3
  - pip:
    - dvc[s3]
    - pydantic==1.10.11