name: ml_deploy_fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi==0.63.0
  - uvicorn
  - gunicorn
  - pip=23.3.1