n_estimators: 175
data:
  path: data/
  raw_file: census.csv
  clean_file: census_clean.csv
  test_size: 0.20
  sliced_name: slice_output.txt
model:
  model_path: model/
  model_name: model.pkl
  encoder_name: encoder.pkl
  lb_name: lb.pkl
  metric_file: metrics.json
cat_features:
- workclass
- education
- marital-status
- occupation
- relationship
- race
- sex
- native-country
